# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: dorothy 0.0.2.pre ruby lib
# stub: ext/dorothy/machine/extconf.rb

Gem::Specification.new do |s|
  s.name = "dorothy"
  s.version = "0.0.3"

  s.required_rubygems_version = Gem::Requirement.new("> 1.3.1") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib", "ext"]
  s.authors = ["Eric K Idema", "Matt Kimmel", "Grant Speelman"]
  s.date = "2014-05-02"
  s.description = "Dorothy is a z-machine interpreter library.  It's core is C (taken in part from Frotz), the interface is Ruby.  Ideally this project forms the basis for writing interpreters and other tools."
  s.email = "grant.speelman@ubxd.com"
  s.executables = ["dorothy"]
  s.extensions = ["ext/dorothy/machine/extconf.rb"]
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    "COPYING",
    "README",
    "Rakefile",
    "bin/dorothy",
    "ext/dorothy/machine/dictionary.c",
    "ext/dorothy/machine/extconf.rb",
    "ext/dorothy/machine/header.c",
    "ext/dorothy/machine/init.c",
    "ext/dorothy/machine/machine.c",
    "ext/dorothy/machine/machine.h",
    "ext/dorothy/machine/memory.c",
    "ext/dorothy/machine/object.c",
    "ext/dorothy/machine/object_table.c",
    "ext/dorothy/machine/ops_math.c",
    "ext/dorothy/machine/ops_memory.c",
    "ext/dorothy/machine/ops_object.c",
    "ext/dorothy/machine/ops_print.c",
    "ext/dorothy/machine/ops_proc.c",
    "ext/dorothy/machine/ops_read.c",
    "ext/dorothy/machine/ops_screen.c",
    "ext/dorothy/machine/ops_todo.c",
    "ext/dorothy/machine/processor.c",
    "ext/dorothy/machine/program.c",
    "ext/dorothy/machine/status.c",
    "lib/dorothy.rb",
    "lib/dorothy/dictionary.rb",
    "lib/dorothy/header.rb",
    "lib/dorothy/machine.rb",
    "lib/dorothy/memory.rb",
    "lib/dorothy/object.rb",
    "lib/dorothy/object_table.rb",
    "lib/dorothy/program.rb",
    "lib/dorothy/random.rb",
    "lib/dorothy/screen.rb",
    "lib/dorothy/status.rb",
    "lib/dorothy/version.rb",
  ]
  s.homepage = "http://github.com/grantspeelman/dorothy"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.2.2"
  s.summary = "Dorothy is a z-machine interpreter library"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<minitest>, [">= 0"])
      s.add_development_dependency(%q<minitest-reporters>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, [">= 0"])
      s.add_development_dependency(%q<bundler>, [">= 0"])
      s.add_development_dependency(%q<rake>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<rake-compiler>, [">= 0"])
    else
      s.add_dependency(%q<minitest>, [">= 0"])
      s.add_dependency(%q<minitest-reporters>, [">= 0"])
      s.add_dependency(%q<rdoc>, [">= 0"])
      s.add_dependency(%q<bundler>, [">= 0"])
      s.add_dependency(%q<rake>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<rake-compiler>, [">= 0"])
    end
  else
    s.add_dependency(%q<minitest>, [">= 0"])
    s.add_dependency(%q<minitest-reporters>, [">= 0"])
    s.add_dependency(%q<rdoc>, [">= 0"])
    s.add_dependency(%q<bundler>, [">= 0"])
    s.add_dependency(%q<rake>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<rake-compiler>, [">= 0"])
  end
end

